### ISSUE TITLE
Can't install Node-Red-Contrib-Harmony-websocket

### ISSUE THREAD

**Issue by UserRG** [lopelex/node-red-contrib-harmony#15]
There's an Error occure, when I install the Version 2.2.3. 
I had a lower Version, so I updatet to Version 2.2.3.  I try it.
After the Error the Nodes where gone completely.
I try to install again with Version 2.2.3 and I startet Node Red new a few times. The Error still occures.

Here is the Log - Can you help me with a solution? Thanks a lot...

-----------------------------------------------------------
2020-09-29T16:58:32.946Z installieren : node-red-contrib-harmony-websocket 2.2.3

2020-09-29T16:58:32.164Z npm install --no-package-lock --global-style --no-audit --no-update-notifier --no-fund --save --save-prefix="~" --production node-red-contrib-harmony-websocket@2.2.3
2020-09-29T16:58:44.199Z [err] npm
2020-09-29T16:58:44.200Z [err]  WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
2020-09-29T16:58:44.204Z [err] npm
2020-09-29T16:58:44.205Z [err]  WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
2020-09-29T16:58:54.389Z [err] npm
2020-09-29T16:58:54.390Z [err]  WARN deprecated har-validator@5.1.5: this library is no longer supported
2020-09-29T17:00:10.218Z [out] 
2020-09-29T17:00:10.218Z [out] > bufferutil@4.0.1 install /usr/local/addons/redmatic/var/node_modules/node-red-contrib-harmony-websocket/node_modules/bufferutil
2020-09-29T17:00:10.218Z [out] > node-gyp-build
2020-09-29T17:00:10.218Z [out] 
2020-09-29T17:00:15.700Z [err] gyp
2020-09-29T17:00:15.701Z [err]  
2020-09-29T17:00:15.701Z [err] ERR! find Python 
2020-09-29T17:00:15.701Z [err] gyp ERR!
2020-09-29T17:00:15.701Z [err]  find Python Python is not set from command line or npm configuration
2020-09-29T17:00:15.701Z [err] gyp 
2020-09-29T17:00:15.702Z [err] ERR! find Python Python is not set from environment variable PYTHON
2020-09-29T17:00:15.702Z [err] gyp ERR!
2020-09-29T17:00:15.702Z [err]  find Python checking if "python" can be used
2020-09-29T17:00:15.702Z [err] gyp ERR!
2020-09-29T17:00:15.702Z [err]  find Python - "python" is not in PATH or produced an error
2020-09-29T17:00:15.702Z [err] gyp ERR! 
2020-09-29T17:00:15.703Z [err] find Python checking if "python2" can be used
2020-09-29T17:00:15.703Z [err] gyp ERR! find Python - "python2" is not in PATH or produced an error
2020-09-29T17:00:15.703Z [err] gyp ERR! find Python checking if "python3" can be used
2020-09-29T17:00:15.703Z [err] gyp ERR! 
2020-09-29T17:00:15.703Z [err] find Python - "python3" is not in PATH or produced an error
2020-09-29T17:00:15.703Z [err] gyp ERR! find Python 
2020-09-29T17:00:15.703Z [err] gyp
2020-09-29T17:00:15.703Z [err]  ERR! find Python **********************************************************
2020-09-29T17:00:15.703Z [err] gyp 
2020-09-29T17:00:15.704Z [err] ERR! find Python You need to install the latest version of Python.
2020-09-29T17:00:15.704Z [err] gyp 
2020-09-29T17:00:15.704Z [err] ERR! find Python Node-gyp should be able to find and use Python. If not,
2020-09-29T17:00:15.704Z [err] gyp ERR!
2020-09-29T17:00:15.704Z [err]  find Python you can try one of the following options:
2020-09-29T17:00:15.704Z [err] gyp ERR! 
2020-09-29T17:00:15.704Z [err] find Python - Use the switch --python="/path/to/pythonexecutable"
2020-09-29T17:00:15.704Z [err] gyp ERR! 
2020-09-29T17:00:15.704Z [err] find Python   (accepted by both node-gyp and npm)
2020-09-29T17:00:15.704Z [err] gyp ERR! 
2020-09-29T17:00:15.705Z [err] find Python - Set the environment variable PYTHON
2020-09-29T17:00:15.705Z [err] gyp ERR! find Python
2020-09-29T17:00:15.705Z [err]  - Set the npm configuration variable python:
2020-09-29T17:00:15.705Z [err] gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
2020-09-29T17:00:15.705Z [err] gyp ERR! find Python For more information consult the documentation at:
2020-09-29T17:00:15.705Z [err] gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
2020-09-29T17:00:15.705Z [err] gyp ERR! find Python **********************************************************
2020-09-29T17:00:15.706Z [err] gyp ERR! find Python 
2020-09-29T17:00:15.708Z [err] gyp
2020-09-29T17:00:15.709Z [err]  ERR! configure error 
2020-09-29T17:00:15.710Z [err] gyp 
2020-09-29T17:00:15.710Z [err] ERR! stack Error: Could not find any Python installation to use
2020-09-29T17:00:15.710Z [err] gyp ERR! stack     at PythonFinder.fail (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
2020-09-29T17:00:15.710Z [err] gyp ERR! stack     at PythonFinder.runChecks (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
2020-09-29T17:00:15.710Z [err] gyp
2020-09-29T17:00:15.711Z [err]  ERR! stack     at PythonFinder.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
2020-09-29T17:00:15.711Z [err] gyp 
2020-09-29T17:00:15.711Z [err] ERR! stack     at PythonFinder.execFileCallback (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
2020-09-29T17:00:15.711Z [err] gyp ERR! 
2020-09-29T17:00:15.711Z [err] stack     at exithandler (child_process.js:315:5)
2020-09-29T17:00:15.711Z [err] gyp ERR! 
2020-09-29T17:00:15.711Z [err] stack     at ChildProcess.errorhandler (child_process.js:327:5)
2020-09-29T17:00:15.711Z [err] gyp ERR! stack
2020-09-29T17:00:15.712Z [err]      at ChildProcess.emit (events.js:314:20)
2020-09-29T17:00:15.712Z [err] gyp ERR! stack
2020-09-29T17:00:15.712Z [err]      at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
2020-09-29T17:00:15.712Z [err] gyp ERR! stack     at onErrorNT (internal/child_process.js:464:16)
2020-09-29T17:00:15.712Z [err] gyp
2020-09-29T17:00:15.712Z [err]  ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
2020-09-29T17:00:15.713Z [err] gyp 
2020-09-29T17:00:15.713Z [err] ERR! System Linux 4.14.34
2020-09-29T17:00:15.713Z [err] gyp
2020-09-29T17:00:15.714Z [err]  ERR! command "/usr/local/addons/redmatic/bin/node" "/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2020-09-29T17:00:15.714Z [err] gyp
2020-09-29T17:00:15.714Z [err]  ERR! cwd /usr/local/addons/redmatic/var/node_modules/node-red-contrib-harmony-websocket/node_modules/bufferutil
2020-09-29T17:00:15.714Z [err] gyp
2020-09-29T17:00:15.714Z [err]  ERR! node -v v14.9.0
2020-09-29T17:00:15.714Z [err] gyp ERR! node-gyp -v v5.1.0
2020-09-29T17:00:15.714Z [err] gyp ERR! not ok 
2020-09-29T17:00:22.291Z [err] npm
2020-09-29T17:00:22.291Z [err]  WARN node-red-project@0.0.1 No repository field.
2020-09-29T17:00:22.334Z [err] npm 
2020-09-29T17:00:22.335Z [err] WARN node-red-project@0.0.1 No license field.
2020-09-29T17:00:22.336Z [err] 
2020-09-29T17:00:22.411Z [err] npm
2020-09-29T17:00:22.411Z [err]  ERR! code ELIFECYCLE
2020-09-29T17:00:22.411Z [err] npm ERR! errno
2020-09-29T17:00:22.411Z [err]  1
2020-09-29T17:00:22.429Z [err] npm 
2020-09-29T17:00:22.430Z [err] ERR! bufferutil@4.0.1 install: `node-gyp-build`
2020-09-29T17:00:22.430Z [err] npm ERR! Exit status 1
2020-09-29T17:00:22.430Z [err] npm
2020-09-29T17:00:22.430Z [err]  ERR! 
2020-09-29T17:00:22.430Z [err] npm ERR!
2020-09-29T17:00:22.430Z [err]  Failed at the bufferutil@4.0.1 install script.
2020-09-29T17:00:22.430Z [err] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-29T17:00:22.818Z [err] 
2020-09-29T17:00:22.819Z [err] npm ERR! A complete log of this run can be found in:
2020-09-29T17:00:22.819Z [err] npm ERR!     /usr/local/addons/redmatic/npm-cache/_logs/2020-09-29T17_00_22_596Z-debug.log
2020-09-29T17:00:22.872Z rc=1

**Comment by hoeni** [comment]
same here!

**Comment by lopelex** [comment]
replace request-promise with node-fetch

**Comment by lopelex** [comment]
plz update to 2.2.4

**Comment by hoeni** [comment]
Does this need some special push or registration to make this version available to be installed from node red itself?
When using Node Red's Web GUI to install it still shows me the 2.2.3 as latest.
Also on https://flows.nodered.org/node/node-red-contrib-harmony-websocket it shows version 2.2.3 (however the badge shows 2.2.4, but I suppose thats an independent link).

**Comment by ristomatti** [comment]
@hoeni For me the flows.nodered.org listing shows version 2.2.4. Nowadays the nodes listed on Node-RED's own index require logging an and requesting an update to a specific module. I believe you could do it yourself by signing in there with your GitHub account. And if there's issue, NR forum is the place to report this: https://discourse.nodered.org/.
