### ISSUE TITLE
Unable to install from Node-Red Palette

### ISSUE THREAD

**Issue by Mikypan81** [lopelex/node-red-contrib-harmony#17]
Hello, I've tryed today to install your palette in node-red, but I receive always same error:

```
2020-11-06T12:34:58.305Z Install : node-red-contrib-harmony-websocket 2.2.4

2020-11-06T12:34:58.350Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix="~" --production node-red-contrib-harmony-websocket@2.2.4
2020-11-06T12:35:11.089Z [out] 
2020-11-06T12:35:11.089Z [out] > bufferutil@4.0.2 install /config/node-red/node_modules/bufferutil
2020-11-06T12:35:11.089Z [out] > node-gyp-build
2020-11-06T12:35:11.089Z [out] 
2020-11-06T12:35:13.258Z [err] gyp
2020-11-06T12:35:13.259Z [err]  
2020-11-06T12:35:13.259Z [err] ERR! build error 
2020-11-06T12:35:13.260Z [err] gyp
2020-11-06T12:35:13.260Z [err]  ERR!
2020-11-06T12:35:13.261Z [err]  stack
2020-11-06T12:35:13.261Z [err]  Error: not found: make
2020-11-06T12:35:13.261Z [err] gyp ERR!
2020-11-06T12:35:13.261Z [err]  stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-11-06T12:35:13.261Z [err] gyp ERR! 
2020-11-06T12:35:13.261Z [err] stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-11-06T12:35:13.261Z [err] gyp ERR!
2020-11-06T12:35:13.262Z [err]  stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-11-06T12:35:13.262Z [err] gyp
2020-11-06T12:35:13.262Z [err]  ERR! stack
2020-11-06T12:35:13.262Z [err]      at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-11-06T12:35:13.262Z [err] gyp 
2020-11-06T12:35:13.262Z [err] ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-11-06T12:35:13.262Z [err] gyp ERR!
2020-11-06T12:35:13.262Z [err]  stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-11-06T12:35:13.262Z [err] gyp
2020-11-06T12:35:13.262Z [err]  ERR! stack     at FSReqCallback.oncomplete (fs.js:168:21)
2020-11-06T12:35:13.263Z [err] gyp
2020-11-06T12:35:13.263Z [err]  ERR! System Linux 4.19.127-v7l
2020-11-06T12:35:13.263Z [err] gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2020-11-06T12:35:13.264Z [err] gyp ERR! cwd
2020-11-06T12:35:13.264Z [err]  /config/node-red/node_modules/bufferutil
2020-11-06T12:35:13.264Z [err] gyp ERR!
2020-11-06T12:35:13.264Z [err]  node -v v12.18.4
2020-11-06T12:35:13.264Z [err] gyp ERR! 
2020-11-06T12:35:13.264Z [err] node-gyp -v v5.1.0
2020-11-06T12:35:13.264Z [err] gyp 
2020-11-06T12:35:13.264Z [err] ERR! not ok 
2020-11-06T12:35:13.831Z [err] npm
2020-11-06T12:35:13.831Z [err]  WARN ts-lib-utils@2.14.2 requires a peer of typescript@2 || 3 || 4 but none is installed. You must install peer dependencies yourself.
2020-11-06T12:35:13.852Z [err] npm
2020-11-06T12:35:13.853Z [err]  WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
2020-11-06T12:35:13.869Z [err] npm 
2020-11-06T12:35:13.869Z [err] WARN type-coverage-core@2.14.2 requires a peer of typescript@2 || 3 || 4 but none is installed. You must install peer dependencies yourself.
2020-11-06T12:35:13.869Z [err] 
2020-11-06T12:35:13.898Z [err] npm
2020-11-06T12:35:13.899Z [err]  ERR! code ELIFECYCLE
2020-11-06T12:35:13.899Z [err] npm
2020-11-06T12:35:13.899Z [err]  ERR! errno 1
2020-11-06T12:35:13.908Z [err] npm
2020-11-06T12:35:13.908Z [err]  ERR! bufferutil@4.0.2 install: `node-gyp-build`
2020-11-06T12:35:13.908Z [err] npm 
2020-11-06T12:35:13.908Z [err] ERR! Exit status 1
2020-11-06T12:35:13.908Z [err] npm ERR!
2020-11-06T12:35:13.908Z [err]  
2020-11-06T12:35:13.908Z [err] npm 
2020-11-06T12:35:13.909Z [err] ERR! Failed at the bufferutil@4.0.2 install script.
2020-11-06T12:35:13.909Z [err] npm 
2020-11-06T12:35:13.909Z [err] ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Can anyone help me, please?

**Comment by lopelex** [comment]
`sudo apt install build-essential`
Try that before installing the pattern. 
Seems like you don't have make installed on your system.

**Comment by Mikypan81** [comment]
I’ve my NodeRED running on hassOs so I can’t use sudo apt...

Inviato da iPhone

**Comment by alphabravocharly72** [comment]
I have the same problem. 
Any solution?
Kind regards
alpha

**Comment by bond2k** [comment]
Same issue running Node Red in Home Assistant on a Raspberry Pi 4 with HassOs. Also tried to install it connecting via ssh to the Home Assistant, but there is not way to execute "sudo" or "apt".

**Comment by lopelex** [comment]
Please test version 2.2.6. 
Have now switched dependencies from websocket to ws.

Hopefully this fixes the problems.

**Comment by bond2k** [comment]
Awesome. This fixed it. Thank you
